"""INTROSPECT — the runtime describing itself, and docs that cannot drift.

Two problems, one module.

The first: everything this agent enforces is decided by code that is not
visible from outside it. Which tools exist, what each may do, which
policy stages run and in what order, what the contracts currently promise,
how often any of it fired. Answering those from the source means reading
six files and trusting that you read them correctly. So `describe()`
returns the whole picture as plain data, and the CLI prints it -- headless,
no session, no API key, no TUI.

The second: documentation drifts. A tool gets an argument, the README does
not. Six months later the docs are confidently wrong, which is worse than
having none, because people believe them. So the tool reference is
*generated* from the registry, and `docs_current()` compares the generated
text with what is on disk. `run-checks.sh` fails when they differ, which
makes the stale state unreachable rather than merely discouraged.

    python -m fullagent.introspect              everything, as text
    python -m fullagent.introspect tools --json machine-readable
    python -m fullagent.introspect --write-docs regenerate docs/TOOLS.md
    python -m fullagent.introspect --check-docs fail if they are stale
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .contractmanifest import LOCK_NAME, manifest, read_lock
from .policypipeline import DEFAULT_PIPELINE
from .recovery import PLAYBOOKS, STRATEGIES
from .toolcontract import ERROR_CODES, RETRYABLE, build_contracts
from .toolpolicy import (ALL_CAPABILITIES, ROLES, TOOL_CAPABILITIES,
                         ToolPolicy)

DOCS_PATH = Path("docs") / "TOOLS.md"
GENERATED_BANNER = (
    "<!-- Generated by `python -m fullagent.introspect --write-docs`. "
    "Do not edit by hand: run-checks.sh fails when this file and the "
    "registry disagree. -->")

SECTIONS = ("tools", "policy", "contracts", "recovery", "metrics",
            "telemetry")


def _tool_section(registry: dict) -> dict:
    contracts = build_contracts(registry)
    out = []
    for name in sorted(contracts):
        c = contracts[name]
        out.append({
            "name": name,
            "description": c.description,
            "version": c.version,
            "permission": sorted(c.permission),
            "idempotency": c.idempotency,
            "timeout_seconds": c.timeout_seconds,
            "needs_approval": c.needs_approval,
            "destructive": c.destructive,
            "outward_facing": c.outward_facing,
            "errors": sorted(set(c.errors)),
            "retry": c.retry.to_dict(),
            "arguments": _arguments_of(c.input_schema),
        })
    return {"count": len(out), "tools": out}


def _arguments_of(schema: dict) -> list[dict]:
    props = (schema or {}).get("properties") or {}
    required = set((schema or {}).get("required") or ())
    return [{"name": key,
             "type": str(spec.get("type", "any")),
             "required": key in required,
             "description": str(spec.get("description", ""))}
            for key, spec in sorted(props.items())]


def _policy_section(policy: ToolPolicy | None) -> dict:
    out: dict[str, Any] = {
        "stages": list(DEFAULT_PIPELINE.names()),
        "capabilities": list(ALL_CAPABILITIES),
        "roles": {name: {"capabilities": sorted(role.capabilities),
                         "ask": sorted(role.ask_capabilities),
                         "allow_destructive_commands":
                             role.allow_destructive_commands,
                         "ceilings": dict(role.ceilings),
                         "allowed_hosts": list(role.allowed_hosts)}
                  for name, role in sorted(ROLES.items())},
        "manifest": {name: sorted(caps)
                     for name, caps in sorted(TOOL_CAPABILITIES.items())},
    }
    if policy is not None:
        out["active"] = {"role": policy.role.name,
                         "roots": list(policy.roots),
                         "calls_so_far": dict(policy.counts)}
    return out


def _contract_section(registry: dict, root: Path) -> dict:
    current = manifest(build_contracts(registry))
    locked = read_lock(root / LOCK_NAME)
    return {"contract_version": current["contract_version"],
            "digest": current["digest"],
            "locked_digest": (locked or {}).get("digest", ""),
            "in_sync": bool(locked) and
            locked.get("digest") == current["digest"],
            "tools": {name: entry["digest"]
                      for name, entry in current["tools"].items()}}


def _recovery_section() -> dict:
    return {"strategies": list(STRATEGIES),
            "codes": {code: {"retryable": RETRYABLE[code],
                             **PLAYBOOKS[code].to_dict()}
                      for code in ERROR_CODES}}


def _metrics_section(dispatcher) -> dict:
    if dispatcher is None:
        return {"available": False}
    m = dispatcher.metrics
    return {"available": True,
            "calls": dict(m.calls), "failures": dict(m.failures),
            "errors_by_code": dict(m.errors_by_code),
            "retries": m.retries, "denials": m.denials,
            "approvals_requested": m.approvals_requested,
            "approvals_refused": m.approvals_refused,
            "registered": len(dispatcher.contracts),
            "available_tools": list(dispatcher.negotiate().available)}


def _telemetry_section(telemetry, prompt: str = "main") -> dict:
    if telemetry is None:
        return {"available": False}
    return {"available": True,
            "prompt": prompt,
            "scorecards": [c.to_dict() for c in telemetry.scorecards(prompt)],
            "drifting": [c.model for c in telemetry.drifting(prompt)],
            "proposals": [p.to_dict() for p in telemetry.proposals]}


def describe(registry: dict | None = None, policy: ToolPolicy | None = None,
             dispatcher=None, telemetry=None, root: str | Path = ".",
             sections: tuple[str, ...] = SECTIONS) -> dict:
    """The whole runtime as plain data. Reads nothing it cannot see."""
    if registry is None:
        from .tools import build_registry
        registry = build_registry()
    root = Path(root)
    out: dict[str, Any] = {}
    if "tools" in sections:
        out["tools"] = _tool_section(registry)
    if "policy" in sections:
        out["policy"] = _policy_section(policy)
    if "contracts" in sections:
        out["contracts"] = _contract_section(registry, root)
    if "recovery" in sections:
        out["recovery"] = _recovery_section()
    if "metrics" in sections:
        out["metrics"] = _metrics_section(dispatcher)
    if "telemetry" in sections:
        out["telemetry"] = _telemetry_section(telemetry)
    return out


def format_description(data: dict) -> str:
    """The same picture, for a person reading a terminal."""
    lines: list[str] = []
    tools = data.get("tools")
    if tools:
        lines.append(f"TOOLS — {tools['count']} registered")
        for t in tools["tools"]:
            flags = []
            if t["needs_approval"]:
                flags.append("approval")
            if t["destructive"]:
                flags.append("destructive")
            if t["outward_facing"]:
                flags.append("outward")
            tail = f"  [{', '.join(flags)}]" if flags else ""
            lines.append(f"  {t['name']:<18} {', '.join(t['permission']) or '-':<28}"
                         f" {t['idempotency']}{tail}")
    policy = data.get("policy")
    if policy:
        lines.append("")
        lines.append("POLICY — stages in order")
        lines.append("  " + " -> ".join(policy["stages"]))
        active = policy.get("active")
        if active:
            lines.append(f"  active role '{active['role']}' "
                         f"rooted at {', '.join(active['roots'])}")
        for name, role in policy["roles"].items():
            ask = f" (asks: {', '.join(role['ask'])})" if role["ask"] else ""
            lines.append(f"  {name:<10} {', '.join(role['capabilities'])}{ask}")
    contracts = data.get("contracts")
    if contracts:
        lines.append("")
        state = "in sync" if contracts["in_sync"] else "OUT OF SYNC with the lock file"
        lines.append(f"CONTRACTS — v{contracts['contract_version']}, "
                     f"digest {contracts['digest']} ({state})")
    recovery = data.get("recovery")
    if recovery:
        lines.append("")
        lines.append(f"RECOVERY — {len(recovery['codes'])} codes")
        for code, book in recovery["codes"].items():
            retry = "retryable" if book["retryable"] else "final"
            lines.append(f"  {code:<14} {book['strategy']:<11} {retry}")
    metrics = data.get("metrics")
    if metrics and metrics.get("available"):
        lines.append("")
        total = sum(metrics["calls"].values())
        lines.append(f"METRICS — {total} call(s), "
                     f"{sum(metrics['failures'].values())} failed, "
                     f"{metrics['retries']} retried, "
                     f"{metrics['denials']} denied")
    telemetry = data.get("telemetry")
    if telemetry and telemetry.get("available"):
        lines.append("")
        lines.append(f"TELEMETRY — {len(telemetry['scorecards'])} model(s)")
        for card in telemetry["scorecards"]:
            score = card["score"]
            lines.append(f"  {card['model']:<18} {card['grade']:<9} "
                         f"{score if score is not None else '-'}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Living documentation
# ---------------------------------------------------------------------------

def render_tool_docs(registry: dict | None = None) -> str:
    """The tool reference, generated from the registry it documents."""
    if registry is None:
        from .tools import build_registry
        registry = build_registry()
    contracts = build_contracts(registry)
    lines = ["# Tool reference", "", GENERATED_BANNER, "",
             f"{len(contracts)} tools. Each one's schema, permission class "
             f"and error set is derived from its registry entry in",
             "`fullagent/tools.py`, so this page cannot describe a tool "
             "differently from the way it actually behaves.", ""]

    lines.append("| Tool | Needs | Repeatable | Approval | Errors |")
    lines.append("|---|---|---|---|---|")
    for name in sorted(contracts):
        c = contracts[name]
        lines.append(
            f"| `{name}` | {', '.join(sorted(c.permission)) or '—'} "
            f"| {c.idempotency} "
            f"| {'yes' if c.needs_approval else 'no'} "
            f"| {len(set(c.errors))} |")
    lines.append("")

    for name in sorted(contracts):
        c = contracts[name]
        lines.append(f"## `{name}`")
        lines.append("")
        lines.append(c.description)
        lines.append("")
        args = _arguments_of(c.input_schema)
        if args:
            lines.append("| Argument | Type | Required | Meaning |")
            lines.append("|---|---|---|---|")
            for a in args:
                lines.append(
                    f"| `{a['name']}` | {a['type']} "
                    f"| {'yes' if a['required'] else 'no'} "
                    f"| {a['description'] or '—'} |")
        else:
            lines.append("Takes no arguments.")
        lines.append("")
        facts = [f"**Needs:** {', '.join(sorted(c.permission)) or 'nothing'}",
                 f"**Repeatable:** {c.idempotency}",
                 f"**Timeout:** {c.timeout_seconds:g}s",
                 f"**Approval:** {'required' if c.needs_approval else 'not required'}"]
        if c.retry.max_attempts > 1:
            facts.append(f"**Retry:** up to {c.retry.max_attempts} attempts "
                         f"on {', '.join(c.retry.codes)}")
        lines.append(" · ".join(facts))
        lines.append("")
        lines.append(f"**Can fail with:** "
                     f"{', '.join(f'`{e}`' for e in sorted(set(c.errors)))}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def docs_current(path: str | Path | None = None,
                 registry: dict | None = None) -> tuple[bool, str]:
    """Is the generated reference on disk still what the registry says?"""
    target = Path(path) if path else DOCS_PATH
    rendered = render_tool_docs(registry)
    try:
        on_disk = target.read_text(encoding="utf-8")
    except OSError:
        return False, f"{target} does not exist"
    if on_disk == rendered:
        return True, f"{target} matches the registry"
    return False, (f"{target} is stale; regenerate it with "
                   f"`python -m fullagent.introspect --write-docs`")


def write_tool_docs(path: str | Path | None = None,
                    registry: dict | None = None) -> Path:
    target = Path(path) if path else DOCS_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_tool_docs(registry), encoding="utf-8")
    return target


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _cli(argv: list[str]) -> int:
    from .tools import build_registry

    root = Path(__file__).resolve().parent.parent
    registry = build_registry()

    if "--write-docs" in argv:
        target = write_tool_docs(root / DOCS_PATH, registry)
        print(f"wrote {target.relative_to(root)} — {len(registry)} tools")
        return 0
    if "--check-docs" in argv:
        ok, why = docs_current(root / DOCS_PATH, registry)
        print(("DOCS CURRENT — " if ok else "DOCS STALE — ") + why)
        return 0 if ok else 1

    wanted = tuple(a for a in argv if not a.startswith("-")) or SECTIONS
    unknown = [w for w in wanted if w not in SECTIONS]
    if unknown:
        print(f"unknown section(s): {', '.join(unknown)}; "
              f"choose from {', '.join(SECTIONS)}")
        return 2
    policy = ToolPolicy("developer", roots=(str(root),))
    data = describe(registry, policy, root=root, sections=wanted)
    print(json.dumps(data, indent=2, sort_keys=True) if "--json" in argv
          else format_description(data))
    return 0


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        raise SystemExit(_cli(sys.argv[1:]))

    # ------------------------------------------------------------------
    # Self-test
    # ------------------------------------------------------------------
    import tempfile

    from .dispatch import Dispatcher
    from .telemetry import Telemetry
    from .tools import build_registry

    root = Path(__file__).resolve().parent.parent
    registry = build_registry()
    work = Path(tempfile.mkdtemp(prefix="fa-introspect-"))

    # --- every section is present and plain data -----------------------
    data = describe(registry, root=root)
    assert set(data) == set(SECTIONS), sorted(data)
    json.dumps(data)   # raises if anything in here is not serialisable

    assert data["tools"]["count"] == len(registry)
    names = {t["name"] for t in data["tools"]["tools"]}
    assert names == set(registry), names ^ set(registry)

    # --- the described policy is the one that actually runs ------------
    assert data["policy"]["stages"] == list(DEFAULT_PIPELINE.names())
    assert set(data["policy"]["roles"]) == set(ROLES)
    for name, role in ROLES.items():
        assert data["policy"]["roles"][name]["capabilities"] == \
            sorted(role.capabilities)

    policy = ToolPolicy("readonly", roots=(str(work),))
    scoped = describe(registry, policy, root=root, sections=("policy",))
    assert scoped["policy"]["active"]["role"] == "readonly"
    assert set(scoped) == {"policy"}, "a section filter must filter"

    # --- contracts report whether they match the lock file -------------
    assert data["contracts"]["in_sync"], \
        "the checked-in lock file disagrees with the registry"
    assert len(data["contracts"]["tools"]) == len(registry)

    # --- recovery describes every code in the taxonomy -----------------
    assert set(data["recovery"]["codes"]) == set(ERROR_CODES)
    for code, book in data["recovery"]["codes"].items():
        assert book["strategy"] in STRATEGIES
        assert book["retryable"] == RETRYABLE[code]

    # --- metrics and telemetry appear once something has run -----------
    assert data["metrics"] == {"available": False}
    dispatcher = Dispatcher(policy=ToolPolicy("developer", roots=(str(work),)),
                            approve=lambda c, a: True)
    dispatcher.register_registry(registry, build_contracts(registry))
    dispatcher.call("list_dir", {"path": str(work)})
    live = describe(registry, dispatcher=dispatcher, root=root,
                    sections=("metrics",))
    assert live["metrics"]["available"] and live["metrics"]["calls"]["list_dir"] == 1

    tel = Telemetry()
    for _ in range(12):
        tel.observe("a-model", 0.95)
    with_models = describe(registry, telemetry=tel, root=root,
                           sections=("telemetry",))
    assert with_models["telemetry"]["scorecards"][0]["model"] == "a-model"

    # --- the text rendering says something about each part -------------
    text = format_description(describe(registry, policy, dispatcher, tel,
                                       root=root))
    for heading in ("TOOLS", "POLICY", "CONTRACTS", "RECOVERY", "METRICS",
                    "TELEMETRY"):
        assert heading in text, heading

    # --- generated docs describe every tool, and detect staleness ------
    rendered = render_tool_docs(registry)
    for name in registry:
        assert f"## `{name}`" in rendered, f"{name} is missing from the docs"
    assert GENERATED_BANNER in rendered
    assert render_tool_docs(registry) == rendered, \
        "doc generation is not deterministic"

    target = work / "TOOLS.md"
    ok, why = docs_current(target, registry)
    assert not ok and "does not exist" in why, why

    write_tool_docs(target, registry)
    ok, why = docs_current(target, registry)
    assert ok, why

    target.write_text(rendered + "\nsomeone edited this by hand\n")
    ok, why = docs_current(target, registry)
    assert not ok and "stale" in why, why

    # a tool added to the registry makes the docs stale immediately
    from .tools import Tool
    extra = dict(registry)
    extra["brand_new_tool"] = Tool(
        "brand_new_tool", "invented for this test",
        {"type": "object", "properties": {}}, lambda **kw: "")
    write_tool_docs(target, registry)
    ok, why = docs_current(target, extra)
    assert not ok, "a new tool must make the generated docs stale"

    print(format_description(describe(registry, policy, root=root,
                                      sections=("policy", "contracts"))))
    print(f"INTROSPECT SELF-TEST PASS — {len(registry)} tools, "
          f"{len(SECTIONS)} sections, {len(rendered.splitlines())} doc lines")
